### ISSUE TITLE
Support for resetting cpufreq stats

### ISSUE THREAD

**Issue by kdrag0n** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#103]
Newer kernels (>= v4.10) have support for resetting the cpufreq stats table on a per-policy basis.

Writing anything to the `reset` node under `stats` for a given policy will clear the stats table for that policy. For example, writing `1` to `/sys/devices/system/cpu/cpufreq/policy0/stats/reset` would reset stats for the little cluster.

**Comment by kdrag0n** [comment]
The change is trivial to backport to older kernels too, so for those who want it: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ee7930ee27fe

**Comment by franciscofranco** [comment]
Good idea.

**Comment by franciscofranco** [comment]
Added for the next release.
