### ISSUE TITLE
Backup kernel naming

### ISSUE THREAD

**Issue by jancm** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#106]
https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/issues/101 is fixed, for the most part. Thanks.

The only (Minor) problem (Minor if you realize that's what caused it) that remains is that you can't create a backup that contains parentheses in the name. Not sure about any other characters, although I know that + works ok.

**Comment by franciscofranco** [comment]
Fixed for the next release.
