### ISSUE TITLE
Little Cluster frequency drop.

### ISSUE THREAD

**Issue by jignesh071** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#109]
I am nameless kernel on lenovo z2 plus and everytime when I restart my phone, little cluster frequency drop down to 844mhz.

**Comment by franciscofranco** [comment]
Not app related.

**Comment by jignesh071** [comment]
It's an app related because with kernel auditor such thing doesn't happen.

Still if you say this is not app related then don't know what to say but KA
is better in this regards.

Thanks & Regards
Jignesh Panchal
Palanpur, Gujarat, India
☎️ +919898704540
