### ISSUE TITLE
Force close when clicking notification channel of BatteryMonitor

### ISSUE THREAD

**Issue by ngmathiou** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#11]
Device: Redmi Note 5
Root: Magisk v18.1
ROM: Pixel Experience 9.0 CAF
Error Description: Clicking on the notification channel of Battery monitor results in force close and not opening activity of Battery Monitor
Log: [pastebin](https://pastebin.com/jfAjYzsW)
App version: 3.12.9
 
Don't know if it's know bug or not even related with FK Manager just thought to give the log just in case.

**Comment by franciscofranco** [comment]
Fixed for 3.12.10.
