### ISSUE TITLE
App settings backup

### ISSUE THREAD

**Issue by Djumie** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#113]
There's a issue with the xml created when the backup of app settings are made. They are not restoring the parameters values but only enabling those options to boot. The values are there in the xml but the app don't recognize them.

**Comment by franciscofranco** [comment]
That's correct, it only saves the values that have been saved to be restored on boot. It's pretty much an impossible mission to save any other thing since they all change per-device and are by the hundreds. I only save values when they're set on boot.

Working as intended.
