### ISSUE TITLE
Battery status disappearing for a while after theme changing

### ISSUE THREAD

**Issue by groozchique** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#116]
Battery status won't show up after changing a theme until it updates.
Video: https://gfycat.com/cleversparklingboto
I was able to reproduce that in 4.7.3 and 4.7.4 as well.

**Comment by franciscofranco** [comment]
Interesting. Will check and fix!

**Comment by franciscofranco** [comment]
Fixed for 4.7.5.
