### ISSUE TITLE
High Brightness Mode

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#12]
Device: OnePlus 5
ROM: OxygenOS Latest Beta
Kernel: https://github.com/whoknowswhoiam/weebmsm8998-pie
Branch: pie-r2

Steps to reproduce:
1) Open FKM
2) Go to Display Settings
3) Go to HBM
4) It'll say ON but still, stay OFF.
5) Turn it off and on and it'll ENABLE HBM.

Repeat steps 1-4
5) Turn it OFF, go back to display settings and back into HBM, it'll turn ON again but still stay OFF.

The issue was reproduced by kdrag0n on proton as well.

**Comment by franciscofranco** [comment]
Fixed for 3.12.10.
