### ISSUE TITLE
HBM with panel text stripped

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#14]
Device: OnePlus 5
FKM Version: 3.12.10
ROM: OxygenOS Latest Beta (Reproduced on others too)
Kernel: https://github.com/whoknowswhoiam/weebmsm8998-pie
Branch: 9.0
Commit: https://github.com/whoknowswhoiam/weebmsm8998-pie/commit/2b627101654e74938c234f20a9cbaea5e94821ef

If the panel text for HBM is stripped, as shown above, the HBM toggle acts incorrectly.
1. Open FKM
2. Go to display settings
3. Open HBM
4. By default, it is OFF (Actually OFF), toggle it ON and it'll enable (Actually ON).
5. Go back and enter HBM again, it'll say OFF (Actually ON), if you toggle it'll say ON (Actually ON), toggling it a 2nd time disables it (Actually OFF as well).

It works fine without the aforementioned commit, but some ROMs require it to make HBM work so I wondered if you could work around it.
Thanks!

**Comment by franciscofranco** [comment]
Should be fixed for the next release.
