### ISSUE TITLE
6.1.1 does not work exept for battery stats

### ISSUE THREAD

**Issue by Hinfty** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#144]
Since V6.1.1, most of the app has stopped working for me.
Battery stats are okay, but most of the app does not show info or settings anymore (Screenshots). 

Device: Oneplus2 on LOS 17.1
![Screenshot_20201129-142629_Franco_Kernel_Manager](https://user-images.githubusercontent.com/69263521/100543217-1a4d2280-324f-11eb-84cf-216000b012fa.png)
![Screenshot_20201129-142622_Franco_Kernel_Manager](https://user-images.githubusercontent.com/69263521/100543218-1b7e4f80-324f-11eb-8886-0ee851894dfe.png)

**Comment by Jdnsh** [comment]
![Uploading Screenshot_20220630-092729_Franco_Kernel_Manager.png…]()
My problem
