### ISSUE TITLE
Per-app profile issue

### ISSUE THREAD

**Issue by MalwareDot** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#161]
when creating a new per-app profile and launching the applied apps
it works at the first time after closing and opening the applied apps it isn't working
note: clearing the FKM app data and re-creating the per-app profile works again for once

⚠️
Edit: it's just not compatible with the miui rom (stock rom/kernel)
now I'm using it on aosp rom with NGK kernel (custom) it all works perfectly

**Comment by jaswinprakash** [comment]
I have the same issue , also I found these error in accessibility section 
![IMG_20220829_181716](https://user-images.githubusercontent.com/103166116/187208636-abc19fc3-23aa-47da-8edc-68777c9751a3.jpg)
![IMG_20220829_181707](https://user-images.githubusercontent.com/103166116/187208647-bef89e5f-1053-4df7-8ff8-79c5e6833ee5.jpg)

**Comment by MalwareDot** [comment]
mine even the accessibility option stays ON but
still it won't work
just 1 time after clear data
![Screenshot_2022-08-29-20-16-48-831_com android settings](https://user-images.githubusercontent.com/108222967/187258639-0e652f54-4826-4a1e-a4ab-6ff2dc2dd578.jpg)
