### ISSUE TITLE
Governor profile

### ISSUE THREAD

**Issue by Remicaa** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#18]
The governor profile doesn't seem to work.

![Screenshot_2019-03-23-10-51-20-927_com franco kernel](https://user-images.githubusercontent.com/30981243/54861424-1e772c00-4d5b-11e9-9641-c2a3e6fd05cb.png)
Steps:
1. Tap on "create a new profile"
2. Enter profile name
3. Tap "ok"

Nothing happened

**Comment by franciscofranco** [comment]
Hmm. I just tried with all my devices and it worked fine. Which device you're on? What's the app version you're on?

**Comment by Remicaa** [comment]
App version : 4.0.2 (1903221853)
Device : mi max 2 
Rom : Miui 9.3.21
Android version : 7.1.1

Or am I missing a step to create one?

**Comment by franciscofranco** [comment]
Can you check if the profile is in /sdcard/franco.kernel_updater/governor_profiles/ after you save it?

**Comment by Remicaa** [comment]
It's not there, but if I put a blank file there, its showed up in the app

**Comment by Remicaa** [comment]
Sorry miss clicked

**Comment by franciscofranco** [comment]
I really can't reproduce. I made some improvements for robustness for version 4.1. Re-open this if it's still "broken" after I release 4.1.
