### ISSUE TITLE
Sultan's Msm Simple Thermal

### ISSUE THREAD

**Issue by Remicaa** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#19]
Can you add support for sultan's simple thermal? 

https://github.com/kerneltoast/android_kernel_oneplus_msm8996/commit/e0354064f81ed563ce0f8efada43a1cbeb52fde8

**Comment by franciscofranco** [comment]
Ok.

**Comment by franciscofranco** [comment]
I'm not gonna add this, it's an old patch from 2015 and it really shouldn't be used anymore.

**Comment by Remicaa** [comment]
Its fine, i just discovered that i can add custom tuneable on your app, i just need the on/off switch, thanks for your great app ^^

**Comment by franciscofranco** [comment]
:)
