### ISSUE TITLE
Additional display tunables

### ISSUE THREAD

**Issue by kdrag0n** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#2]
## General
| Path | Name | Type | Values | Default |
| -----|------|------|----------| ---|
| `/sys/module/msm_drm/parameters/flickerfree_enabled` | PWM Flickerfree mod for OLED displays | `uint` | `0` (off), `1` (on) | `N`
| `/sys/module/msm_drm/parameters/backlight_dimmer` | Backlight dimmer | `bool` | `N` (off), `Y` (on) | `N`

## [KLapse](https://github.com/tanish2k09/KLapse-Livedisplay)
| Path | Description | Value(s) | Default |
| -----|------|----------| -----|
| `/sys/klapse/enable_klapse` | A switch to enable or disable klapse | 0 = off, 1 = on, 2 = brightness-dependent mode | `0` |
| `/sys/klapse/klapse_start_hour` | The hour at which klapse should start scaling the RGB values from daytime to target (see next points) | [0, 23] | `17` |
| `/sys/klapse/klapse_stop_hour` | The hour by which klapse should scale back the RGB values from target to daytime (see next points) | [0, 23] | `7` |
| `/sys/klapse/daytime_[r,g,b]` | The RGB set that must be used for all the time outside of start and stop hour range | [0, 256] | `256,256,256` |
| `/sys/klapse/target_[r,g,b]` | The RGB set that must be scaled towards for all the time inside of start and stop hour range | [0, 256] | `256,202,151` |
| `/sys/klapse/klapse_scaling_rate` | Controls how soon the RGB reaches from daytime to target inside of start and stop hour range. Once target is reached, it remains constant till 30 minutes before stop hour, where target RGB scales back to daytime RGB | ¯\\\_(ツ)\_/¯ | `30` |
| `/sys/klapse/brightness_factor` | From the name itself, this value has the ability to bend perception and make your display appear as if it is at a lesser brightness level than it actually is at. It works by reducing the RGB values by the same factor | [2, 10] (10 means accurate brightness, 5 means 50% of current brightness, etc) | `10` |
| `/sys/klapse/brightness_factor_auto` | A switch that allows you to automatically set the brightness factor in a set time range | 0 = off, 1 = on | `0` |
| `/sys/klapse/brightness_factor_auto_start_hour` | The hour at which brightness_factor should be applied. Depends on `brightness_factor_auto` = 1. | [0, 23] | `23` |
| `/sys/klapse/brightness_factor_auto_stop_hour` | The hour at which brightness_factor should be reverted to 10. Depends on `brightness_factor_auto` = 1. | [0, 23] | `6` |
| `/sys/klapse/backlight_range` | The brightness range within which klapse should scale from daytime to target_rgb. Depends on `enable_klapse` = 2. | [2, 1023] (first value is lower and second is upper, `lower < upper` must be true) | `2 200` |
| `/sys/klapse/pulse_freq` | The amount of milliseconds after which klapse_pulse is called. A more developer-targeted tunable. Depends on `enable_klapse` = 1 OR `brightness_factor_auto` = 1. | [1000, 600000] (represents 1 sec to 10 minutes) | `30000 ` |
| `/sys/klapse/fadeback_minutes` | The number of minutes before klapse_stop_hour when RGB should start going back to daytime_rgb. Depends on `enable_klapse` = 1. | [2, minutes between `klapse_start_hour` and `klapse_stop_hour`] | `60` |

**Comment by franciscofranco** [comment]
It's been implemented for the upcoming 4.0.
