### ISSUE TITLE
Can't apply negative stune values under stune settings

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#21]
Not sure what else I can add here but literally just that^. Works perfectly fine if I set it as a custom tuneable.

**Comment by obol2** [comment]
I have the same issue

**Comment by franciscofranco** [comment]
Fixed for 4.1. Some entries don't accept signed values, such as schedtune.prefer_idle, but schedtune.boost accepts it, so it's been fixed for the next bigger(ish) release.
