### ISSUE TITLE
Allow custom tuneable to show full path

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#22]
Things like stune boost for different groups end up having the same name and no way to distinguish them without having to go to the menu where I can select the tuneables to delete. Instead, it would be nice if the full path was visible directly, or at least when tapped on to edit.

So, if I add two paths:
1) `/dev/stune/foreground/schedtune.boost`
2) `/dev/stune/background/schedtune.boost`
They'll both show up as `schedtune.boost` which doesn't help the user(s) to differentiate betweeen them unless they actually check what values were change or remember the order.

**Comment by franciscofranco** [comment]
Fixed for 4.1.
