### ISSUE TITLE
Custom Tuneables "don't delete" but actually do!

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#23]
I'll let the video explain it:
https://drive.google.com/open?id=1E3SWLAJl38yrcRxhubkPI89mNnphgAsg
Basically,  even if you hit delete in the list (once you tap the gear icon), it'll just refresh the list but the tuneable still gets deleted.

**Comment by franciscofranco** [comment]
Fixed for 4.1.

**Comment by whoknowswhoiam** [comment]
Broken on 4.3.3
https://photos.app.goo.gl/zWd6SzVF9nsVCH6q9
