### ISSUE TITLE
Minimum brightness

### ISSUE THREAD

**Issue by Dimarv135** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#25]
Can't set value lower than 10%.

**Comment by franciscofranco** [comment]
That's the point to prevent accidents.

**Comment by Dimarv135** [comment]
I suppose by accident you mean so low that is basically black? 10% is really high though. Maybe a 5 would be more appropriate.

**Comment by franciscofranco** [comment]
Yes, that kind of accident. I can lower to "protection" to 5% though.
