### ISSUE TITLE
Battery stats do not reset when needed

### ISSUE THREAD

**Issue by anirudhgupta109** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#28]
Device: OnePlus 6
ROM: AOSiP
Kernel: Inbuilt AOSiP kernel

Battery stats have been set to reset at 98% but when charged over specified level, it didn't seem to reset the stats. 
Screenshots attached.
![Screenshot_FK_Kernel_Manager_20190327-023431](https://user-images.githubusercontent.com/29012333/55033623-997d6280-5039-11e9-8acf-9331331832be.png)
![Screenshot_Settings_20190327-023445](https://user-images.githubusercontent.com/29012333/55033624-997d6280-5039-11e9-963a-3b355504ac3f.png)
![Screenshot_Settings_20190327-023441](https://user-images.githubusercontent.com/29012333/55033626-997d6280-5039-11e9-9caa-8b6545966887.png)

**Comment by franciscofranco** [comment]
Seems to be fixed for 4.1.
