### ISSUE TITLE
overlapping screens bug

### ISSUE THREAD

**Issue by legioncyclops** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#29]
I don't know how it happens but I get this visual bug often on my Nexus 5: 

https://imgur.com/a/QE4LMul

**Comment by legioncyclops** [comment]
A few notes: 
The bug happens (not everytime) when screens are switched (say going from "Per app profiles" to "Kernel Settings") when the back button/triangle button is pressed. It doesn't occur when screens are switched using the menu button (the 3 lines one)... 

ROM is Resurrection Remix for Android 8.1

**Comment by franciscofranco** [comment]
Tricky one but should be fixed for 4.1.
