### ISSUE TITLE
CPU Input Boost: general boost frequencies are broken

### ISSUE THREAD

**Issue by kdrag0n** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#3]
General boost CPU frequency tunables in cpu_input_boost were added recently, but they are broken.
 - They have the same titles as input boost frequencies (`Cluster #1 CPU input-boost`), which is incorrect. General boost is a separate pair of frequencies and boost level that is used for screen updates as a replacement for input boost which generally uses higher frequencies. The title should be closer to `Cluster #1 CPU general boost`, maybe with a brief explanation that it is usually used for when the screen updates, if there is sufficient space in the UI to prevent this from ruining UX.
 - They show the raw KHz value that sysfs shows instead of user-friendly MHz values that are shown for input boost frequencies, e.g. `825600` instead of `825 MHz`.
 - They are dysfunctional - attempting to set a value for them does absolutely nothing.

**Comment by franciscofranco** [comment]
This should be fixed for 3.12.10. Re-open if this is still fucked.
