### ISSUE TITLE
Skip counting % if drops soon after boot

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#32]
If a user boots, say after flashing a kernel at 80%. It's likely that after boot the device will still be at 80% but actually almost about to drop to 79%. What I've observed is, in my case it dropped to 79% after 5s and FKM did actually ignore it, but when it dropped to 78% it took the drop to 79 into account so my active came up as around 19% rather than 9-10~ thus giving an inaccurate reading for future values.

**Comment by franciscofranco** [comment]
I can't reproduce this with the changes I made on version 4.1 beta 1.2.
