### ISSUE TITLE
Inconsistency in LMK presets

### ISSUE THREAD

**Issue by groozchique** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#33]
By default, values for LMK settings are in *Megabytes*, but when you're trying to change it via dialog window – numbers are different, so it's not that convenient as it meant to be.

Also as UX improvement, you can add arrows to LMK values like you did in *Display control*, so it's easier to tune them precisely.

![Screenshot_FK_Kernel_Manager_20190330-191109](https://user-images.githubusercontent.com/28346376/55278741-36354e00-5321-11e9-87ef-c8eb7ed05f9c.png)
![Screenshot_FK_Kernel_Manager_20190330-191120](https://user-images.githubusercontent.com/28346376/55278743-3a616b80-5321-11e9-8822-236bcc5038bf.png)

**Comment by franciscofranco** [comment]
Agreed, will fix for the next release.

**Comment by franciscofranco** [comment]
Fixed for 4.1.
