### ISSUE TITLE
Klapse settings

### ISSUE THREAD

**Issue by gansaid** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#36]
Device: OnePlus 5T
ROM: OxygenOS Latest 
Kernel: FK-r44

Klapse settings (start and end times, durations, red blue and green levels) reset after every reboot

**Comment by franciscofranco** [comment]
I can't reproduce on all my +20 devices. Every setting is properly re-applied on boot. That said, I can make improvements to the boot service and make it more reliable.

**Comment by franciscofranco** [comment]
Improvements added for 4.1.

**Comment by kocane** [comment]
@franciscofranco  using latest version and latest kernel on my OP6, I experience this as well. On reboot, k-lapse is disabled. I've tried toggling things some times and I've tried setting "set on boot" both before and after I configure k-lapse but it doesn't help.
