### ISSUE TITLE
Random locks

### ISSUE THREAD

**Issue by kgursu** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#38]
After applying kernel r22, I experienced 2 or 3 random locks, which lead to reboot on my Pocophone F1 with latest release of Global Pie MIUI Rom (ver. 10.2.3.0).
How to troubleshoot this issue?
r22 is way better than r21, but it still needs some fixes. 

Thanks.

**Comment by franciscofranco** [comment]
This is not the place for such report. And I can't reproduce any lockups on my Pocophone.
