### ISSUE TITLE
License Not Valid

### ISSUE THREAD

**Issue by Mchar7** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#39]
I purchased the FK Kernel Manager app through Google Play, but when I open it, I get a message that my license is not valid.

I am using microG on my ROM, so I don;t have any proprietary Google software installed. All other apps have been running perfectly fine and can still interact with my Google account; this app seems to be the only exception.

I refunded it in the meantime but would love to buy it again if you could fix this. Thanks.

**Comment by franciscofranco** [comment]
Hi. The app uses the standard licensing from Google to verify the purchase so I don't really know what to tell you :/
