### ISSUE TITLE
Night Shift always disabled 

### ISSUE THREAD

**Issue by Primokorn** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#40]
Hi
I manually enable night shift from the display settings but it's automatically disabled a few seconds later.
Can I always force the use of Night Shift? 
Thank you. 

OnePlus 3T
Android 9 using Skydragon rom

**Comment by franciscofranco** [comment]
Night Shift works fine, just tested on my OP3T. I can only guess you have some other feature that's suplanting it, like LiveDisplay or something.

**Comment by Primokorn** [comment]
You are right. Everything seems to work fine now.
