### ISSUE TITLE
Performance Profiles Unsupported 

### ISSUE THREAD

**Issue by DenyDarko** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#41]
Hey @franciscofranco :)

I'm having a kinda weird issue on my OP6. 

Performance Profiles are unavailable while I'm on r15.

Attaching some screenshots and a logcat. 

![Screenshot_20190411-003226](https://user-images.githubusercontent.com/3320229/55915133-91085880-5bf1-11e9-98eb-d0c99d6100fa.jpg)
![Screenshot_20190411-003231](https://user-images.githubusercontent.com/3320229/55915137-95347600-5bf1-11e9-8cbd-78874023831e.jpg)

[logcat_04-11-2019_00-32-19.txt](https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/files/3065957/logcat_04-11-2019_00-32-19.txt)

**Comment by franciscofranco** [comment]
Hi. You need to flash the Kernel AFTER flashing magisk.

**Comment by DenyDarko** [comment]
Well that's how I did it and it worked at the beginning xD

I guess I need to reflash the kernel after every Magisk update as I just reflashed kernel and it worked. 

How about a check in Kernel Manager about that and a warning if kernel needs reinstall? 😁
