### ISSUE TITLE
BMB slider % visual glitch

### ISSUE THREAD

**Issue by paschfire** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#48]
Adjust BMB slider to any value say 50%, then exit/enter the Display control menu, value shown is <9% lower, so now showing 41%.
50% is still set even though 41% is being displayed.

Seems to be a visual glitch only.

Device;
OP3T ~ OOS-5.0.8 ~ Magisk 19.0 Canary ~ FKr46 ~ FKM v4.1b3

**Comment by franciscofranco** [comment]
Fixed for 4.1.
