### ISSUE TITLE
GPU control not working

### ISSUE THREAD

**Issue by Alexey71** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#49]
Xiaomi redmi note 4, lineageos 15.1. GPU settings not change. I try other app it's fine
/sys/class/kgsl/kgsl-3d0
/sys/devices/soc/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0

**Comment by franciscofranco** [comment]
What are you trying to change? I just tried on my Mido running LOS 15.1 and it changed min gpu freq and it worked just fine.

**Comment by franciscofranco** [comment]
I can't reproduce on any device. Please re-open this with more information if you want.

**Comment by Alexey71** [comment]
GPU Maximum frequency and GPU Governor can not changed

https://drive.google.com/file/d/1IhlYBkAgvp806wTlT8ee3lM8mCvSsR12/view?usp=sharing
