### ISSUE TITLE
Backlight dimmer set-on-boot toggle visual glitch

### ISSUE THREAD

**Issue by paschfire** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#51]
Transfering over previous bug report from Slack.

Backlight dimmer within display control menu, if set-on-boot toggle is enabled, exit/enter Display Control menu, toggle resets back to disabled position.

 Set-on-boot service still remains enabled and working after device reboot, regardless of set-on-boot toggle position. Visual glitch only.

**Comment by franciscofranco** [comment]
Fixed for 4.1.
