### ISSUE TITLE
Vibration intensity setting missing

### ISSUE THREAD

**Issue by incognico** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#53]
I own FK manager since a long time and just tried it again but I miss the option to lessen/modify the general vibration intensity. It used to be there. Currently I need to use the "Kernel Auditor" app in addition just for that :(

Please re-add :)

**Comment by franciscofranco** [comment]
I need a little more information... device, app version, etc

**Comment by incognico** [comment]
OnePlus 5, latest FK from play store. Linage OS, Magisk. 

On April 23, 2019 10:56:03 PM GMT+02:00, Francisco Franco <notifications@github.com> wrote:
>I need a little more information... device, app version, etc
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/issues/53#issuecomment-485971058

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by franciscofranco** [comment]
Hmm it's right here on my OP5 and OP5T. Check 4.1 going up in a few minutes, I revamped the vibration settings. Re-open if it's still fucked.

**Comment by incognico** [comment]
It's there now, thanks!

On April 24, 2019 7:04:38 PM GMT+02:00, Francisco Franco <notifications@github.com> wrote:
>Hmm it's right here on my OP5 and OP5T. Check 4.1 going up in a few
>minutes, I revamped the vibration settings. Re-open if it's still
>fucked.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/issues/53#issuecomment-486335001

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
