### ISSUE TITLE
Discharging and charging ampere is showing positive and negative respectively. 

### ISSUE THREAD

**Issue by souvikpodder** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#54]
Discharging ampere is showing in positive.
And charging ampere is showing in negative.
Phone= poco f1
Rom= eu miui beta 9.4.18
![Screenshot_2019-04-26-20-06-29-870_com android chrome](https://user-images.githubusercontent.com/11691954/56815758-b89d2900-685f-11e9-88b8-af34693457c1.png)

**Comment by franciscofranco** [comment]
I can't reproduce. Is that on the latest 4.0 version of the app?

**Comment by Terrigible** [comment]
Might be kernel/ROM related. I experience this on OP6 Havoc-OS with SmurfKernel.
