### ISSUE TITLE
App crashes when opening Kernel settings

### ISSUE THREAD

**Issue by abhijit1998** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#55]
When trying to open kernel settings the app is crashing. please look into this.
[logs-2019-04-30-21-40-58.zip](https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/files/3132143/logs-2019-04-30-21-40-58.zip)

**Comment by franciscofranco** [comment]
Fixed for 4.1.1 rolling out now.
