### ISSUE TITLE
Plugging in my phone didn't reset stats

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#58]
![image](https://user-images.githubusercontent.com/31561543/57075309-1c57a400-6cef-11e9-8b9e-b1f9e12b55af.png)
![image](https://user-images.githubusercontent.com/31561543/57075317-2083c180-6cef-11e9-9786-4e55bc8054b4.png)

**Comment by franciscofranco** [comment]
Can't reproduce on all my 20 devices. Always resets when plugging in. My code is correct too. Unless your rom isn't sending the correct broadcast when the device is plugged in.
