### ISSUE TITLE
FK crash

### ISSUE THREAD

**Issue by DenyDarko** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#59]
Hey @franciscofranco 

By clicking on manage profiles, boom, immediately crash:
![Screenshot_20190511-195113](https://user-images.githubusercontent.com/3320229/57572675-5e3ac580-7426-11e9-8272-e422730ee51c.jpg)

Logcat:

[logcat_05-11-2019_19-52-18.txt](https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/files/3169269/logcat_05-11-2019_19-52-18.txt)

**Comment by franciscofranco** [comment]
Yup, fixing it. Thanks & sorry.

**Comment by DenyDarko** [comment]
Fixed in last version
