### ISSUE TITLE
White mode is automatically being applied.

### ISSUE THREAD

**Issue by paschfire** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#62]
![Screenshot_20190518-071750](https://user-images.githubusercontent.com/10088235/57969001-a5054f80-793f-11e9-90c2-d4be40b3c44a.jpg)
![Screenshot_20190518-071941](https://user-images.githubusercontent.com/10088235/57969002-a5054f80-793f-11e9-8bca-e968456d7a88.jpg)

Here to report my eyes are broken! 😵

Oh ya... You also cannot disable "White mode"

If you choose Dark and then exit/enter FKM(clear FKM from recent menu) when relaunched the eye bleeding white is applied again. With Dark showing enabled.

#WhiteUIMustDie

**Comment by paschfire** [comment]
Clearing FKM App data seems to have solved the issue for now, Dark mode is remaining applied upon exit/enter FKM.

So might just be a single case issue, if so pls close this ticket.

**Comment by franciscofranco** [comment]
Fixed.
