### ISSUE TITLE
Color Calibration Problems

### ISSUE THREAD

**Issue by NeroOrin** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#63]
Changing the values of the sliders for Saturation, Contrast, Value, and Hue don't do anything. RGB works fine though.

**Comment by franciscofranco** [comment]
It works fine for all my devices. A little more context & information about your device otherwise I can't help. Have you tried screening off/on ? Some devices need that.

**Comment by NeroOrin** [comment]
Even when turning the screen on/off the settings do nothing. It sometimes works but I don't know when. When it does work, whenever I rebootn the device, all the settings wont take effect anymore. I've tried re-installing the manager and re-flashing the kernel.

**Comment by franciscofranco** [comment]
And which device is that? I really can't reproduce no matter what.

**Comment by ibenk76** [comment]
Color calibration not work in pocophone

**Comment by franciscofranco** [comment]
Yes it does. Turn the display off/on.
