### ISSUE TITLE
Battery Monitor Service

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#68]
Device: OnePlus 5
ROM: OxygenOS
Kernel: Weeb Kernel unreleased build
Root status: Unrooted
Issues:
1. Rebooting the device disables the Battery Manager Service automatically and requires it to be re-enabled by the user again.

While doing this, I was also able to reproduce the battery stats not resetting properly. On the first reboot where I flashed a new kernel from TWRP, I had 1.5 hours of SoT with 1% dropped, implying the previous boot time's SoT was still being accounted for, which it shouldn't since I have that option disabled.
This issue was first brought to your attention here:
https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/issues/58

2. There is no option to get to settings from the Battery Manager Service menu. This means, in order to change a setting, the user would have to root. For example, if a user wanted to change the theme from dark to light, he would have to root.
However, I understand that most of the options in the settings menu are useless when unrooted but I thought it was worth mentioning regardless.

**Comment by baalajimaestro** [comment]
> " This means, in order to change a setting, the user would have to root"

I see no point of a kernel manager without root.

**Comment by whoknowswhoiam** [comment]
> > " This means, in order to change a setting, the user would have to root"
> 
> I see no point of a kernel manager without root.

A bug is a bug nonetheless.

**Comment by franciscofranco** [comment]
I'll make this a bit easier for 4.3.

**Comment by franciscofranco** [comment]
Implemented for 4.3.
