### ISSUE TITLE
Weird-ass flasher bug

### ISSUE THREAD

**Issue by groozchique** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#69]
As I described before, when I flash something from "Download" folder it shows me number, if I flash from other directory – proper file name.

I'm using "Files" app on Pissel Experience ROM.

Video: https://gfycat.com/NeighboringAngelicAmericanbobtail

**Comment by franciscofranco** [comment]
I can't reproduce, looks like a rom bug.
