### ISSUE TITLE
Wake gesture settings are incomplete

### ISSUE THREAD

**Issue by kdrag0n** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#7]
The settings for flar2's wake gestures driver in `Kernel settings` are incomplete:
 - `/sys/android_touch/wake_gestures` "Wake gestures" is not meant to be exposed to the user. 
 - There are vibration settings:

| Path | Name | Values |
| - | - | - |
| `/sys/android_touch/sleep_vibrate` | Vibrate on Sweep2Sleep | 0, 1 |
| `/sys/android_touch/wake_vibrate` | Vibrate on wake | 0, 1 |

**Comment by franciscofranco** [comment]
Done.
