### ISSUE TITLE
OTG communication with PS3 controller not working

### ISSUE THREAD

**Issue by Dionisieplay** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#70]
Hi, I noticed since the last couple of releases that connecting a ps3 controller through OTG won't work on OP5, I have tested with the stock and weeb kernel and it works. It's not a pressing issue but wanted to report it. Btw I'm on OOS 9.0.4.

**Comment by franciscofranco** [comment]
This is for app stuff only. I'll close and I'll check it out later on the op5 kernel.
