### ISSUE TITLE
Battery Monitor Service inaccurate % 

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#71]
Logcat and dmesg: https://drive.google.com/file/d/1-BPRZsfYhwFF5y-qhd3awbbBJorScwnK/view?usp=drivesdk
Pic: https://drive.google.com/file/d/1-ITWN8We4X8omc7_8dejiB-kVQDQFlcb/view?usp=drivesdk

It's been 13 minutes since I unplugged and it doesn't calculate the right % dropped ( 94->92 )
maybe the logs could help xd

**Comment by franciscofranco** [comment]
Can't reproduce on any device.
