### ISSUE TITLE
FKM auto device updated kernel available detector ( dunno what to call this lmao )

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#72]
pic: https://photos.app.goo.gl/DczAW4cuuDC5BFbp7
Basically, this should be warning me that I'm not connected to a network instead of saying that there isn't a kernel available ( OP5 ) when I'm not connected to a network. What it says now is accurate only for unsupported devices.

**Comment by franciscofranco** [comment]
Fixed for 4.3.
