### ISSUE TITLE
Modifying CAF CPU Boost frequency selection behaviour

### ISSUE THREAD

**Issue by buzzcut-1105** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#78]
Currently, changing frequencies for both/two clusters is a little cumbersome, i.e. : 

1. Select the 'Input boost frequency' option 
2. Select new Little cluster frequency 
3. Select the 'Input boost frequency' option 
4. Select new Big cluster frequency 

There is a sudden/jarring transition after selecting a frequency, i.e. between steps 2 and 3, where it closes the selection window, after which you have to return to the frequency selection window again. It just feels a little unintuitive to have a window with two different selection list open to the user, which then closes after selecting an element from only _one_ of those lists. 

What I'd like to suggest is instead of having to repeat Step 1 twice, make it so : 

1. Select the 'Input boost frequency' option
2. Select frequencies for both clusters (without having the window exit)
3. (Maybe) Press a 'Done' button, or something like that?

Or maybe have two different options for Little and Big cluster frequencies separately? Furthermore, I think highlighting the currently selected/applied frequency in the selection list would be an overall positive change, as well.

Not sure how selection for other cpu boost drivers, apart from the CAF one, is implemented - but maybe they're the same? 

In my opinion, adding an explicit 'Done' or 'Update' option would result in a _slightly_ better UX. Would love to hear your thoughts on it!

**Comment by franciscofranco** [comment]
Agreed - will implement. Thanks for your suggestion.

**Comment by franciscofranco** [comment]
Done. Will be released on 4.3.
