### ISSUE TITLE
Battery stats not opening at boot

### ISSUE THREAD

**Issue by johndogless** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#81]
The battery stats dies not open at boot. I know this because there is no battery percentage in the status bar.

The first two tips do not start at boot, even when the setting is selected.

Tips need to selected and started after each boot.

**Comment by franciscofranco** [comment]
I can't reproduce both, but I've made boot service improvements for the upcoming 4.3. Re-open if the issue persists after I release 4.3.

**Comment by johndogless** [comment]
Thanks

⁣John Wright
Pedagogical Technician

Schola physicorum, quo ludi numquam cessant, quod primo numquam coeperunt.​
