### ISSUE TITLE
Duplicate CPU stats

### ISSUE THREAD

**Issue by Remicaa** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#84]
![Screenshot_2019-07-06-13-56-18-046_com franco kernel](https://user-images.githubusercontent.com/30981243/60753118-551a3f00-9ff8-11e9-9cda-44f21b332f84.jpg)

It shows the cpu stats twice when first time opening live monitor, i have cpu stats as default page

**Comment by Remicaa** [comment]
It doesn't happen before 4.3 update,  soc is msm8953

**Comment by Remicaa** [comment]
Still persist in 4.3.1

**Comment by franciscofranco** [comment]
Hmm having a hard time reproducing it.

**Comment by Remicaa** [comment]
Sorry i forget to mention this, i set the default "System Health" to cpu frequency stats, it doesn't happen if i set to the other tab , but doesn't seems to happened on stock kernel. Probably a derp in my kernel, you can close this issue if you want

**Comment by Remicaa** [comment]
Fixed in 4.3.3 update , thanks

**Comment by dhruvan2912** [comment]
I'm facing this issue in 4.4.1 
![photo_2019-08-16_21-13-32](https://user-images.githubusercontent.com/53393418/63179959-dee31080-c06a-11e9-846d-c8c3d72e88d8.jpg)
![photo_2019-08-16_21-13-34](https://user-images.githubusercontent.com/53393418/63179960-dee31080-c06a-11e9-8e27-e1d3561fe7f5.jpg)

**Comment by franciscofranco** [comment]
Fixed for the upcoming 4.6.
