### ISSUE TITLE
The tab scrolling/switching is too sensitive

### ISSUE THREAD

**Issue by Y-T-G** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#85]
Many times I try to scroll down but the app considers it as a left/right swipe and switches the tab. The tab switching should handle only the more horizontal swipes in my opinion.

**Comment by franciscofranco** [comment]
That's a bug on Google's ViewPager2 class and it's been reported on their issuetracker. Nothing I can do about it until they fix it.
