### ISSUE TITLE
Incorrect and inconsistent English strings

### ISSUE THREAD

**Issue by kdrag0n** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#9]
Here are a few issues with the English strings in the app, some of which are omnipresent:
 - `Per-App profiles` should be `Per-app profiles`. App should not be captalized.
 - The text at the bottom of the Night Shift page (in Display control) does not end with a period, which is inconsistent with the top text and the sentences within the bottom text.
 - The kernel settings page says `I/0` instead of `I/O`, which looks inconsistent.
 - OOM should be capitalized in the case of `Oom kill allocating task` in kernel settings.
 - Kernel settings -> Wakelock blockers should be renamed to `Wakelock blocker` without the `s`.
 - If no wakelocks are blocked, the wakelock blocker page always displays a single wakelock with an empty name that can be removed by the user, but never actually does so as the wakelock blocker output is being parsed incorrectly.
 - `Wakelocks list` should be renamed to `Wakelock list` or `Find wakelocks` on the wakelock blocker page.
 - On the kernel settings page, all occurrences of `logger` should be changed to `log`. You are reading logs, not interfacing with loggers.
 - `Min free kbytes` in the `Kernel settings` page should be replaced with `Minimum amount of free memory` with the unit as `KiB` appended to the value, similar to how input boost frequencies are shown as `825 MHz` instead of `825`.
 - It may be helpful to change `Cluster #1` to `Little cluster` and `Cluster #2` to `Big cluster` app-wide for users that are not aware of the typical cluster order.
 - `CPU input-boost` should be `CPU input boost`.
 - `Min GPU freq` in `GPU control` should be renamed to `Min GPU frequency` for consistency, as `Max GPU frequency` is right above it.
 - Expanding occurrences of `Max` to `Maximum` and `Min` to `Minimum` may be helpful for improved clarity.
 - The `Well, you haven't backed any kernel yet... But you can start by backing one down there 🙌` message in `Backup & restore` should be changed to `No kernel backups yet. Why not make one?` for proper grammar and alignment with the [Material text guidelines](https://material.io/design/communication/writing.html).
 - `Backup & restore` should be renamed to `Kernel backups` for clarity.
 - `notif icon` should be replaced with `notification icon` on the `Battery monitor` page.
 - You should go through all the strings and make sure that they are compliant with the [Material text guidelines](https://material.io/design/communication/writing.html), *after* making the above changes of choice.

The app should be far more polished overall for English users after these changes are made.

**Comment by franciscofranco** [comment]
Thanks. Most have been implemented. Will go through the entire strings once this big update is out.
