### ISSUE TITLE
Issue #23 again

### ISSUE THREAD

**Issue by whoknowswhoiam** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#92]
Broken on 4.3.3
https://photos.app.goo.gl/zWd6SzVF9nsVCH6q9

Reference https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/issues/23#issue-424627794

**Comment by franciscofranco** [comment]
Fixed for 4.4.
