### ISSUE TITLE
Per-app profile

### ISSUE THREAD

**Issue by maruashok** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#96]
I created new per app profile and than set it for one app and deleted that profile, now when i again try to set per app profile i can still apply that deleted profile.

**Comment by franciscofranco** [comment]
I can't reproduce. Can you show me a screenrecord? Thanks.

**Comment by maruashok** [comment]
Me too not able to reproduce it.
i will contact you if i face it again.
