### ISSUE TITLE
GPU boost value cannot be changed, FKM PP QS tile(Balanced) has possible visual issue.

### ISSUE THREAD

**Issue by paschfire** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#97]
FKM v4.3.4

GPU boost settings can no longer be adjusted. I had it previous set to low, taping on it now does nothing but highlight the option, no overflow menu is shown.

The PP QS tile used to be highlighted using the current system colours, now when set to Balanced it's just grey(inactive). Performance and Battery are still highlighted. Just not sure if this was an intended change made within FKM or not. Screenshots attached to show examples.

OP3T, OOS 9.0.4, FK r48, Magisk 19.4c, FKM v4.3.4

(Balanced PP not highlighted)
https://photos.app.goo.gl/DUtGG16tN1XvveYX9

(GPU boost press it doesn't allow access to overflow menu)
https://photos.app.goo.gl/3QNA2SW7QXTPdXXT6

**Comment by franciscofranco** [comment]
Gpu boost derp is not expected and will fix, the other is intended since Balance profile is the default so it shouldn't be shown as "Active". :)

**Comment by franciscofranco** [comment]
Gpu boost fixed for 4.4.
