### ISSUE TITLE
Minimum notification priority for battery stats Android 7

### ISSUE THREAD

**Issue by tech189** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#98]
Hi,

I'm running this app with no problems on Pie but on my older tablet which I cannot update (it's stuck on 7.1.1) I have no way of stopping the icon appear on my status bar. See my screenshot, where the system settings do not allow me to change priority to minimum. Could you make it so that the notification appears in the same way as AccuBattery in the screenshot (or at least have an option)?

![image](https://user-images.githubusercontent.com/10728085/61786253-2f1cd900-ae05-11e9-9f1f-152d1eb791d2.png)

Thanks!

**Comment by franciscofranco** [comment]
Not planned. Sorry!
