### ISSUE TITLE
Bug: Incorrect input type for stune boost > cpus

### ISSUE THREAD

**Issue by xzr467706992** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#99]
The "cpus" node allows value like "0-1" "0-2,5". But once I set the value to a number-only value like "0" , the input type would be change to number , thus I cant input anything like "-" or "," .

**Comment by franciscofranco** [comment]
Will fix, thanks.

**Comment by franciscofranco** [comment]
Fixed for the upcoming 4.6.
